# -*- coding: utf-8 -*-
"""Konversi gambar untuk OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xX09k7Tcpnw2mfMJAGm-nBjGirKFlK1b
"""

!pip install requests

import requests
import json
from google.colab import files

import requests
import json
from google.colab import files
from IPython.display import Image, display

# Mengunggah berkas
uploaded = files.upload()

# Menampilkan gambar yang diunggah
image_filename = list(uploaded.keys())[0]
display(Image(filename=image_filename))

# Menentukan URL OCR
url = "https://ocr.asprise.com/api/v1/receipt"

# Memilih berkas yang diunggah
image_filename = list(uploaded.keys())[0]

# Melakukan permintaan POST ke API OCR
res = requests.post(url,
                    data={
                        'api_key': 'TEST',
                        'recognizer': 'auto',
                        'ref_no': 'oct_python_123'
                    },
                    files={
                        'file': (image_filename, open(image_filename, 'rb'))
                    })

# Menyimpan respons ke dalam file JSON
with open("response.json", "w") as f:
    json.dump(json.loads(res.text), f)

# Membuka berkas response.json
with open("response.json", "r") as f:
    data = json.load(f)
print()

# Menampilkan informasi dari respons OCR
items = data['receipts'][0]['items']

print(f"Daftar Pembelian Anda di {data['receipts'][0]['merchant_name']}")

for item in items:
    print(f"{item['description']} - {data['receipts'][0]['currency']} {item['amount']}")

print("-" * 30)
print(f"Subtotal: {data['receipts'][0]['currency']} {data['receipts'][0]['subtotal']}")
print(f"Tax: {data['receipts'][0]['currency']} {data['receipts'][0]['tax']}")
print("-" * 30)
print(f"Total: {data['receipts'][0]['currency']} {data['receipts'][0]['total']}")